Enum classificacao {
  Livre
  _10
  _12
  _14
  _16
  _18
}

Enum status_obra {
  Rascunho
  Privado
  Publico
}

Enum tipo_interacao {
  curtida
  salvo
  clique
  comentario
}

Enum tipo_usuario {
  Autor
  Leitor
  Editora
}

Enum verificacao_cnpj {
  Negado
  Verificado
  Pendente
}

Table usuarios [headercolor: #175e7a] {
  id integer [pk, increment, not null, unique]
  email varchar [not null]
  senha_hash bytea [not null]
  tipo_usuario tipo_usuario [not null]
  ativo boolean [not null]
  criado_em timestamp [not null]
  atualizado_em timestamp [not null]

  indexes {
    (id) [name: "usuario_index_0"]
  }
}

Table perfis [headercolor: #175e7a] {
  id_perfil integer [pk, increment, not null, unique]
  id_usuario integer [not null]
  criado_em timestamp [not null]
  atualizado_em timestamp [not null]

  indexes {
    (id_usuario) [name: "perfis_index_0"]
  }
}

Ref: perfis.id_usuario > usuarios.id

Table perfil_leitor [headercolor: #175e7a] {
  id_leitor integer [pk, increment, not null, unique]
  id_perfil integer [not null]
  apelido varchar(200) [not null]
  data_nascimento date [not null]
  foto_perfil_url text
  bio varchar(400)
  criado_em timestamp [not null]
  atualizado_em timestamp [not null]
}

Ref: perfil_leitor.id_perfil > perfis.id_perfil

Table perfil_autor [headercolor: #175e7a] {
  id_autor integer [pk, increment, not null, unique]
  id_perfil integer [not null]
  pseudonimo varchar(150) [not null]
  nome_autor varchar(200) [not null]
  data_nascimento date [not null]
  foto_perfil_url text
  bio varchar(400)
  criado_em timestamp [not null]
  atualizado_em timestamp [not null]
}

Ref: perfil_autor.id_perfil > perfis.id_perfil

Table perfil_editora [headercolor: #175e7a] {
  id_editora integer [pk, increment, not null, unique]
  id_perfil integer [not null]
  nome_fantasia varchar(200) [not null]
  cnpj char(14) [not null]
  cnpj_verificado verificacao_cnpj [not null, default: "Pendente"]
  site_oficial varchar(150)
  foto_perfil_url text
  bio varchar(400)
  criado_em timestamp [not null]
  atualizado_em timestamp [not null]
}

Ref: perfil_editora.id_perfil > perfis.id_perfil

Table obras [headercolor: #175e7a] {
  id_obra integer [pk, increment, not null, unique]
  id_autor integer [not null]
  titulo varchar(200) [not null]
  sinopse varchar(500) [not null]
  trecho_de_amostra varchar(500)
  capa_url text [default: "uploads/img/capas/capa_padrao.png"]
  pdf_url text [not null]
  status_obra status_obra [not null, default: "Rascunho"]
  classificacao_indicativa classificacao [not null]
  criado_em timestamp [not null]
  atualizado_em timestamp [not null]
}

Ref: obras.id_autor > perfil_autor.id_autor

Table tags [headercolor: #175e7a] {
  id_tag integer [pk, increment, not null, unique]
  nome_tag varchar(100) [not null, unique]
}

Table obra_tags [headercolor: #175e7a] {
  id_obra integer [not null]
  id_tag integer [not null]

  indexes {
    (id_obra, id_tag) [pk, name: "obra_tags_pkey"]
  }
}

Ref: obra_tags.id_obra > obras.id_obra
Ref: obra_tags.id_tag > tags.id_tag

Table interacoes [headercolor: #175e7a] {
  id_interacao integer [pk, increment, not null, unique]
  id_perfil integer [not null]
  id_obra integer [not null]
  tipo tipo_interacao [not null]
  conteudo text
  criado_em timestamp [not null]
}

Ref: interacoes.id_perfil > perfis.id_perfil
Ref: interacoes.id_obra > obras.id_obra

Table mensagens [headercolor: #175e7a] {
  id_mensagem integer [pk, increment, not null, unique]
  id_remetente integer [not null]
  id_destinatario integer [not null]
  conteudo text [not null]
  enviado_em timestamp [not null]
  lido boolean [not null, default: false]
}

Ref: mensagens.id_remetente > perfis.id_perfil
Ref: mensagens.id_destinatario > perfis.id_perfil

Table recomendacoes_feed [headercolor: #175e7a] {
  id_recomendacao integer [pk, increment, not null, unique]
  id_perfil integer [not null]
  id_obra integer [not null]
  peso real [not null]
  algoritmo_versao varchar(50)
  parametros jsonb
  criado_em timestamp [not null]
}

Ref: recomendacoes_feed.id_perfil > perfis.id_perfil
Ref: recomendacoes_feed.id_obra > obras.id_obra

Table seguidores [headercolor: #175e7a] {
  id_seguidor integer [not null]
  id_seguido integer [not null]
  criado_em timestamp [not null]
}

Ref: seguidores.id_seguidor > perfis.id_perfil
Ref: seguidores.id_seguido > perfis.id_perfil
